### ISSUE TITLE
Make function URLs more visible in console output

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-functions-cli#213]
Add a newline before and after the URLs, and add a header and indention. Possibly use a different color, such as cyan.

**Comment by ahmelsayed** [comment]
like this 

```
HttpFunctions:

    Function1: http://localhost:7071/api/function1

    Function2: http://localhost:7071/api/function2

    Function3: http://localhost:7071/api/function3

```
